import type { AtlasDef } from "../atlasDefs.ts";

export const CustomAtlas: AtlasDef = {
    compress: true,
    images: [
        "loot/loot-weapon-lasr-gun.svg",
        "loot/loot-weapon-double-lasr-gun.svg",
        "loot/loot-weapon-m2010.svg",
        "loot/loot-weapon-pkm.svg",
        "loot/loot-weapon-m82.svg",
        "loot/loot-weapon-p90.svg",
        "loot/loot-perk-melee-master.svg",
        "loot/loot-weapon-sw500.svg",
        "loot/loot-perk-energized.svg",
        "loot/loot-weapon-dp12.svg",
        "loot/loot-perk-closer.svg",
        "loot/loot-perk-holy-shield.svg",
        "loot/loot-weapon-m96.svg",
        "loot/loot-weapon-m79.svg",
        "loot/loot-perk-vampire.svg",
        "guns/gun-pkm-01.svg",
        "guns/gun-dp12-01.svg",
        "guns/gun-splitter-01.svg",
        "guns/gun-m96-01.svg",
        "guns/gun-m79-01.svg",
        "guns/gun-lasr-gun.svg",
        "proj/proj-coconut-pellet-01.svg",
        "proj/proj-40mm-01.svg",
    ],
};
