name: Lint

on:
  push:
    branches:
      - master
    paths: &paths
      - "**.js"
      - "**.ts"
      - "**.json"
      - "**.css"
      - "**.yaml"
      - ".github/workflows/lint.yml"

  pull_request:
    paths: *paths

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    concurrency: ci-lint-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Install Packages
        run: pnpm install

      - name: Run oxlint
        run: pnpm exec oxlint --max-warnings 0

      - name: Run dprint
        if: always()
        run: pnpm exec dprint check
